// OTOMATİK ÜRETİLDİ — elle düzenlemeyin.
// Kaynak: scripts/buildProvinceNeighbors.mjs (public/geojson/turkey-provinces.geojson)
// Yeniden üretmek için: node scripts/buildProvinceNeighbors.mjs

export const provinceNeighbors: Record<string, string[]> = {
  "Adana": ["Hatay", "Kahramanmaraş", "Kayseri", "Mersin", "Niğde", "Osmaniye"],
  "Adıyaman": ["Diyarbakır", "Gaziantep", "Kahramanmaraş", "Malatya", "Şanlıurfa"],
  "Afyonkarahisar": ["Burdur", "Denizli", "Eskişehir", "Isparta", "Konya", "Kütahya", "Uşak"],
  "Ağrı": ["Bitlis", "Erzurum", "Iğdır", "Kars", "Muş", "Van"],
  "Aksaray": ["Ankara", "Kırşehir", "Konya", "Nevşehir", "Niğde"],
  "Amasya": ["Çorum", "Samsun", "Tokat", "Yozgat"],
  "Ankara": ["Aksaray", "Bolu", "Çankırı", "Eskişehir", "Kırıkkale", "Kırşehir", "Konya"],
  "Antalya": ["Burdur", "Isparta", "Karaman", "Konya", "Mersin", "Muğla"],
  "Ardahan": ["Artvin", "Erzurum", "Kars"],
  "Artvin": ["Ardahan", "Erzurum", "Rize"],
  "Aydın": ["Denizli", "İzmir", "Manisa", "Muğla"],
  "Balıkesir": ["Bursa", "Çanakkale", "İzmir", "Kütahya", "Manisa"],
  "Bartın": ["Karabük", "Kastamonu", "Zonguldak"],
  "Batman": ["Bitlis", "Diyarbakır", "Mardin", "Muş", "Siirt", "Şırnak"],
  "Bayburt": ["Erzincan", "Erzurum", "Gümüşhane", "Rize", "Trabzon"],
  "Bilecik": ["Bolu", "Bursa", "Eskişehir", "Kocaeli", "Kütahya", "Sakarya"],
  "Bingöl": ["Diyarbakır", "Elazığ", "Erzincan", "Erzurum", "Muş", "Tunceli"],
  "Bitlis": ["Ağrı", "Batman", "Muş", "Siirt", "Van"],
  "Bolu": ["Ankara", "Bilecik", "Çankırı", "Düzce", "Eskişehir", "Karabük", "Sakarya", "Zonguldak"],
  "Burdur": ["Afyonkarahisar", "Antalya", "Denizli", "Isparta", "Muğla"],
  "Bursa": ["Balıkesir", "Bilecik", "Kocaeli", "Kütahya", "Yalova"],
  "Çanakkale": ["Balıkesir", "Edirne", "Tekirdağ"],
  "Çankırı": ["Ankara", "Bolu", "Çorum", "Karabük", "Kastamonu", "Kırıkkale"],
  "Çorum": ["Amasya", "Çankırı", "Kastamonu", "Kırıkkale", "Samsun", "Sinop", "Yozgat"],
  "Denizli": ["Afyonkarahisar", "Aydın", "Burdur", "Manisa", "Muğla", "Uşak"],
  "Diyarbakır": ["Adıyaman", "Batman", "Bingöl", "Elazığ", "Malatya", "Mardin", "Muş", "Şanlıurfa"],
  "Düzce": ["Bolu", "Sakarya", "Zonguldak"],
  "Edirne": ["Çanakkale", "Kırklareli", "Tekirdağ"],
  "Elazığ": ["Bingöl", "Diyarbakır", "Erzincan", "Malatya", "Tunceli"],
  "Erzincan": ["Bayburt", "Bingöl", "Elazığ", "Erzurum", "Giresun", "Gümüşhane", "Malatya", "Sivas", "Tunceli"],
  "Erzurum": ["Ağrı", "Ardahan", "Artvin", "Bayburt", "Bingöl", "Erzincan", "Kars", "Muş", "Rize"],
  "Eskişehir": ["Afyonkarahisar", "Ankara", "Bilecik", "Bolu", "Konya", "Kütahya"],
  "Gaziantep": ["Adıyaman", "Hatay", "Kahramanmaraş", "Kilis", "Osmaniye", "Şanlıurfa"],
  "Giresun": ["Erzincan", "Gümüşhane", "Ordu", "Sivas", "Trabzon"],
  "Gümüşhane": ["Bayburt", "Erzincan", "Giresun", "Trabzon"],
  "Hakkâri": ["Şırnak", "Van"],
  "Hatay": ["Adana", "Gaziantep", "Osmaniye"],
  "Iğdır": ["Ağrı", "Kars"],
  "Isparta": ["Afyonkarahisar", "Antalya", "Burdur", "Konya"],
  "İstanbul": ["Kırklareli", "Kocaeli", "Tekirdağ"],
  "İzmir": ["Aydın", "Balıkesir", "Manisa"],
  "Kahramanmaraş": ["Adana", "Adıyaman", "Gaziantep", "Kayseri", "Malatya", "Osmaniye", "Sivas"],
  "Karabük": ["Bartın", "Bolu", "Çankırı", "Kastamonu", "Zonguldak"],
  "Karaman": ["Antalya", "Konya", "Mersin"],
  "Kars": ["Ağrı", "Ardahan", "Erzurum", "Iğdır"],
  "Kastamonu": ["Bartın", "Çankırı", "Çorum", "Karabük", "Sinop"],
  "Kayseri": ["Adana", "Kahramanmaraş", "Nevşehir", "Niğde", "Sivas", "Yozgat"],
  "Kırıkkale": ["Ankara", "Çankırı", "Çorum", "Kırşehir", "Yozgat"],
  "Kırklareli": ["Edirne", "İstanbul", "Tekirdağ"],
  "Kırşehir": ["Aksaray", "Ankara", "Kırıkkale", "Nevşehir", "Yozgat"],
  "Kilis": ["Gaziantep"],
  "Kocaeli": ["Bilecik", "Bursa", "İstanbul", "Sakarya", "Yalova"],
  "Konya": ["Afyonkarahisar", "Aksaray", "Ankara", "Antalya", "Eskişehir", "Isparta", "Karaman", "Mersin", "Niğde"],
  "Kütahya": ["Afyonkarahisar", "Balıkesir", "Bilecik", "Bursa", "Eskişehir", "Manisa", "Uşak"],
  "Malatya": ["Adıyaman", "Diyarbakır", "Elazığ", "Erzincan", "Kahramanmaraş", "Sivas"],
  "Manisa": ["Aydın", "Balıkesir", "Denizli", "İzmir", "Kütahya", "Uşak"],
  "Mardin": ["Batman", "Diyarbakır", "Siirt", "Şanlıurfa", "Şırnak"],
  "Mersin": ["Adana", "Antalya", "Karaman", "Konya", "Niğde"],
  "Muğla": ["Antalya", "Aydın", "Burdur", "Denizli"],
  "Muş": ["Ağrı", "Batman", "Bingöl", "Bitlis", "Diyarbakır", "Erzurum"],
  "Nevşehir": ["Aksaray", "Kayseri", "Kırşehir", "Niğde", "Yozgat"],
  "Niğde": ["Adana", "Aksaray", "Kayseri", "Konya", "Mersin", "Nevşehir"],
  "Ordu": ["Giresun", "Samsun", "Sivas", "Tokat"],
  "Osmaniye": ["Adana", "Gaziantep", "Hatay", "Kahramanmaraş"],
  "Rize": ["Artvin", "Bayburt", "Erzurum", "Trabzon"],
  "Sakarya": ["Bilecik", "Bolu", "Düzce", "Kocaeli"],
  "Samsun": ["Amasya", "Çorum", "Ordu", "Sinop", "Tokat"],
  "Siirt": ["Batman", "Bitlis", "Mardin", "Şırnak", "Van"],
  "Sinop": ["Çorum", "Kastamonu", "Samsun"],
  "Sivas": ["Erzincan", "Giresun", "Kahramanmaraş", "Kayseri", "Malatya", "Ordu", "Tokat", "Yozgat"],
  "Şanlıurfa": ["Adıyaman", "Diyarbakır", "Gaziantep", "Mardin"],
  "Şırnak": ["Batman", "Hakkâri", "Mardin", "Siirt", "Van"],
  "Tekirdağ": ["Çanakkale", "Edirne", "İstanbul", "Kırklareli"],
  "Tokat": ["Amasya", "Ordu", "Samsun", "Sivas", "Yozgat"],
  "Trabzon": ["Bayburt", "Giresun", "Gümüşhane", "Rize"],
  "Tunceli": ["Bingöl", "Elazığ", "Erzincan"],
  "Uşak": ["Afyonkarahisar", "Denizli", "Kütahya", "Manisa"],
  "Van": ["Ağrı", "Bitlis", "Hakkâri", "Siirt", "Şırnak"],
  "Yalova": ["Bursa", "Kocaeli"],
  "Yozgat": ["Amasya", "Çorum", "Kayseri", "Kırıkkale", "Kırşehir", "Nevşehir", "Sivas", "Tokat"],
  "Zonguldak": ["Bartın", "Bolu", "Düzce", "Karabük"],
};
